### ISSUE TITLE
Macos get an Error that module 'os' has no attribute 'sched_getaffinity'

### ISSUE THREAD

**Issue by Sologala** [saulzar/multical#4]
Hi @saulzar 

I test you multical on macos catalina, get some following  Errors :

``` 
Traceback (most recent call last):
  File "/Users/bytedance/anaconda3/bin/multical", line 3, in <module>
    from multical.app import arguments
  File "/Users/bytedance/anaconda3/lib/python3.8/site-packages/multical/__init__.py", line 19, in <module>
    __all__ = import_submodules(__name__).keys()                        
  File "/Users/bytedance/anaconda3/lib/python3.8/site-packages/multical/__init__.py", line 13, in import_submodules
    return {
  File "/Users/bytedance/anaconda3/lib/python3.8/site-packages/multical/__init__.py", line 14, in <dictcomp>
    name: importlib.import_module(name)
  File "/Users/bytedance/anaconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/bytedance/anaconda3/lib/python3.8/site-packages/multical/camera.py", line 213, in <module>
    def undistort_images(images, cameras, j=len(os.sched_getaffinity(0)), chunksize=4):
AttributeError: module 'os' has no attribute 'sched_getaffinity'

```

It seems like that the method `os.sched_getaffinity ` is only available for linux distributions. 

Is there some way to replace this funciotn ?

**Comment by saulzar** [comment]
Thanks for letting me know - I have replaced it with multiprocessing.cpu_count() which seems to be properly cross platform
